export const SCENE_KEYS = {
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  GAME_SCENE: 'GAME_SCENE',
  UI_SCENE: 'UI_SCENE',
  GAME_OVER_SCENE: 'GAME_OVER_SCENE',
  // Robot simulation scenes
  ROBOT_PRELOAD_SCENE: 'ROBOT_PRELOAD_SCENE',
  ROBOT_SCENE: 'ROBOT_SCENE',
  ROBOT_UI_SCENE: 'ROBOT_UI_SCENE',
  ROBOT_WORLD_BUILDER_SCENE: 'ROBOT_WORLD_BUILDER_SCENE',
} as const;
